#데이터베이스
#Spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    platform: h2
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
      properties:
        hibernate:
          use_sql_comments: true

#h2
h2:
  console:
    enabled: true
    path: /console
    settings:
      trace: false
      web-allow-others: false



---
#logging
logging:
  level:
    org:
      hibernate: info

---
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


---
spring:
  banner:
    location: banner.txt