#데이터베이스
Spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: memong
    password: memong
    driver-class-name: oracle.jdbc.OracleDriver

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
      properties:
        hibernate:
          use_sql_comments: true

#h2
#h2:
#  console:
#    enabled: true
#    path: /console
#    settings:
#      trace: false
#      web-allow-others: false



---
#logging
logging:
  level:
    org:
      hibernate: info
  path: logs

---
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


---
spring:
  banner:
    location: banner.txt